# Generated by Django 5.0.6 on 2024-06-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'managed': True},
        ),
    ]
