# Generated by Django 3.2 on 2024-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$i5V6EJ0S8p8yeaU0dId3n9$3LErFdIJq7uCqg/KDpPP7Kjr7rOE7NsPrDR7b/WiIWk=', max_length=128),
        ),
    ]
