# Generated by Django 5.0.6 on 2024-09-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Rp2IbXheLIlOy0bH6p8xH5$XW/3ApLXrSyTEh+IlaSwnKo1uHglMGKKJzINVCfFrzw=', max_length=128),
        ),
    ]
