# Generated by Django 5.0.6 on 2024-06-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_alter_detail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'managed': False},
        ),
    ]
