# Generated by Django 5.0.6 on 2024-06-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_alter_detail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
