# Generated by Django 3.2 on 2024-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$O7WA4l43MagsLR3P3nFFKF$+ZTJ9WIapmU7HwbRE9bGcjQG0f47ZFcGjLlZjeRz11o=', max_length=128),
        ),
    ]
