# Generated by Django 5.0.6 on 2024-06-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
