# Generated by Django 3.2 on 2024-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$68fosE2rtgFlUesjrTutOD$k+eSOQic32ZA32DZG/97wXNTrSlWvy7LZk2Sh4owAME=', max_length=128),
        ),
    ]
