# Generated by Django 5.0.6 on 2024-09-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$1fZj8yGhllpUxuKEOQrOom$78pGfmS+XZXoPkJuRTijOibJKF7QioT96IfCW9gRcfk=', max_length=128),
        ),
    ]
