# Generated by Django 5.0.6 on 2024-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$69bwA7n81svSf3DLOkDBvb$7ks/LFh4Zz0SRjqKJd3yegqFbqc8b5BSByGUp4SvWCc=', max_length=128),
        ),
    ]
