# Generated by Django 5.0.6 on 2024-06-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userpwd',
            field=models.CharField(max_length=128),
        ),
    ]
