# Generated by Django 5.0.6 on 2024-09-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$4xeB8LpVdprlnAcdzDKjGJ$CH6Zqi/u2YAQ/RijPsDHLFq1gEU2/Mf5ZKWiofBgu64=', max_length=128),
        ),
    ]
