# Generated by Django 5.0.6 on 2024-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_user_date_joined_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$gcibJHbAyjBlaIB8GF0iPm$wzG7ZAd1b5fClMRaQQxBvaNZdjVYIWYN2lCtffcvVnk=', max_length=128),
        ),
    ]
