# Generated by Django 5.0.6 on 2024-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$f2pTxzARhpCkqFa7j1yV4T$x1ji2Tf3YeqxiB6otiKCRoYJ+TuFtUPdJADkVpTtHbg=', max_length=128),
        ),
    ]
