# Generated by Django 5.0.6 on 2024-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$VxFCaMBpjJT94eSR65ON1B$QInsjmDod8I/bP02rIVFgn6sHhRGYiMHjczA7epXH+g=', max_length=128),
        ),
    ]
