# Generated by Django 5.0.6 on 2024-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$J1bgs8iMHyyR2maGLDtKAz$ti0QRnvnmKvy+vVua7MfMqQ9xqhLc0QzRYR6jqv1eJo=', max_length=128),
        ),
    ]
