# Generated by Django 5.0.6 on 2024-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$nD1PjAzz1IMuaRfBpgp4B9$9ynDV8QHi6iWnWIoE4a5w3310Yezz/zbaZARbDChPRQ=', max_length=128),
        ),
    ]
