# Generated by Django 5.0.6 on 2024-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Xl63DLdl3VWLBH3cvXeoRX$DWylpGc02d5ymmFTL/OHdaZMTBKnG4mNzz6d6fQIw4c=', max_length=128),
        ),
    ]
