# Generated by Django 5.0.6 on 2024-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$aPmn5wEu94kfgO5kpxLL8b$B1TZ3K6iwuYQixrWjD5Mpn8KtTBHgZpbdJmTpNYB/us=', max_length=128),
        ),
    ]
