# Generated by Django 5.0.6 on 2024-09-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0013_situationcategory_situationkeyword_delete_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='situation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='situationcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='situationkeyword',
            options={'managed': False},
        ),
    ]
