# Generated by Django 5.0.6 on 2024-09-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0014_alter_goods_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='situationcategory',
            table='situationCategory',
        ),
        migrations.AlterModelTable(
            name='situationkeyword',
            table='situationKeyword',
        ),
    ]
