# Generated by Django 5.0.6 on 2024-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0015_alter_situationcategory_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodsKeyword',
            fields=[
                ('goodsKwKey', models.AutoField(primary_key=True, serialize=False)),
                ('goodsKeyword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'goodsKeyword',
                'managed': False,
            },
        ),
    ]
