# Generated by Django 5.0.6 on 2024-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$iOCo76J64Dmh6N7WR1txRA$cw7AtrQy0c/xcO8pH3zd232dEzNSQO/NuwFdwWbtUGA=', max_length=128),
        ),
    ]
