# Generated by Django 5.0.6 on 2024-06-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$pYH9Yhs9qwWgxJKlsJI262$hcI0kyCkuRapdW184JUx1tfIJPd/sPLxhLdF3MWJjDY=', max_length=128),
        ),
    ]
