# Generated by Django 5.0.6 on 2024-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0018_alter_user_groups_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$lO9YGtd2l2aqOk3WVTNIOa$J2Ota9S16jtfnFLo+VfCEXG2Y/9L2k8wXPeYAxae8rA=', max_length=128),
        ),
    ]
