# Generated by Django 5.0.6 on 2024-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0019_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$KjvaeUxX0zCHLUEBdW8Bql$KNIQDidnj3WyelhVdkCadcLrQQkKjvvgIjcuaey8E0s=', max_length=128),
        ),
    ]
