# Generated by Django 5.0.6 on 2024-06-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$ZStfojbMnqzBJfUMySYjAy$rn74wSg9qDPLuR/Oi9tqeVhvdZFUQdACATsEWhWRnEw=', max_length=128),
        ),
    ]
