# Generated by Django 5.0.6 on 2024-06-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$tDAmM2VBeGRDJ67J5Zk87l$RbpMtskcDGiVqlGQ1vUbD94uj+YfZp8pHz2la4WQE9w=', max_length=128),
        ),
    ]
