# Generated by Django 5.0.6 on 2024-07-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$i1BhiyVDHIG7napdTSMl1W$ep79Oms7fCMmrKwTNCUPyf8i/uhtA9vIAslAzZaAS4U=', max_length=128),
        ),
    ]
