# Generated by Django 5.0.6 on 2024-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0023_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$WwzIhlzaDNfm5wa9MAhXo7$P8dsfPw0eO8f4irZT+zPEOT8MWbP1o2EtlNlgz0+ZdA=', max_length=128),
        ),
    ]
