# Generated by Django 5.0.6 on 2024-07-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$X6hGvRFRMnKr2TFfsSD4eE$OQQy4WzVIdmgbpKQAHA8KR4Ci8uW5xj/rPpKjyxosU0=', max_length=128),
        ),
    ]
