# Generated by Django 5.0.6 on 2024-07-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$657w7qtxmx6pQTTkGnBURA$yIK4iA1UyV9gNN/PngQ94NEw8IEBY2tC2nxm3d3N+zk=', max_length=128),
        ),
    ]
