# Generated by Django 5.0.6 on 2024-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$bAh15YH2lMII4okj5fFL1g$ccrngs6vJDPH1mU7qMBotP2QEjqIjVRnAKUsGHWg5Yc=', max_length=128),
        ),
    ]
