# Generated by Django 5.0.6 on 2024-07-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$NxmprbyttVPHO0oEQPKYHL$jCUrkON0u0A6+71vDmV4U22wzswOcmQj2yScyg9g0gQ=', max_length=128),
        ),
    ]
