# Generated by Django 5.0.6 on 2024-07-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0029_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$SqvQFmMkYjM9DC5sw8jjLl$xVuus7+gmsw6H9FuR3XZi0OsKSnZJ1dMeIhdmmlZ0+s=', max_length=128),
        ),
    ]
