# Generated by Django 5.0.6 on 2024-07-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0030_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Wgb8eeWhknyHlO25chT5EV$gfybGlhpUSquNsa5NNrgs0+dyJ3rmsAfkbXdX7rIa2s=', max_length=128),
        ),
    ]
