# Generated by Django 5.0.6 on 2024-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Ca7A9ZxOHBg90S0REtiGK4$8YJS4p3TTNfquLSZq4kG4PwSmfDUx5GLsjBAxruSNoI=', max_length=128),
        ),
    ]
